// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLGQGSASs1XeLV9P3QWUn_vzquzen4O48',
    appId: '1:1026907593971:web:fb1afb7858d754f515ab86',
    messagingSenderId: '1026907593971',
    projectId: 'deartis',
    authDomain: 'deartis.firebaseapp.com',
    storageBucket: 'deartis.appspot.com',
    measurementId: 'G-V4BHR9V8QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQfr29DssvIIdnQafiUVV5YvhjJC5E3YA',
    appId: '1:1026907593971:android:1ee7b2071afe265815ab86',
    messagingSenderId: '1026907593971',
    projectId: 'deartis',
    storageBucket: 'deartis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI_N9fCkcLeoIYTq6RSRaedpMFYobM81g',
    appId: '1:1026907593971:ios:08a184eadef8c74915ab86',
    messagingSenderId: '1026907593971',
    projectId: 'deartis',
    storageBucket: 'deartis.appspot.com',
    androidClientId: '1026907593971-bgrq5a88rvesaf8olo9mgp0u70u9ipqb.apps.googleusercontent.com',
    iosClientId: '1026907593971-105ko2hvqnuh22rv6k373ehp6bf84lkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appClienteRestaurante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI_N9fCkcLeoIYTq6RSRaedpMFYobM81g',
    appId: '1:1026907593971:ios:08a184eadef8c74915ab86',
    messagingSenderId: '1026907593971',
    projectId: 'deartis',
    storageBucket: 'deartis.appspot.com',
    androidClientId: '1026907593971-bgrq5a88rvesaf8olo9mgp0u70u9ipqb.apps.googleusercontent.com',
    iosClientId: '1026907593971-105ko2hvqnuh22rv6k373ehp6bf84lkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appClienteRestaurante',
  );
}
